language: python
sudo: required
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
before_install:
  - mv openprocurement/auction/worker/tests/data/auction_worker_travis.yaml openprocurement/auction/worker/tests/data/auction_worker_defaults.yaml
install:
  - pip install -r requirements.txt
  - curl -X PUT 0.0.0.0:5984/auctions
script:
  - bin/pytest .
